### ISSUE TITLE
Any plans to update to 1.7 given 1.6 is being deprecated?

### ISSUE THREAD

**Issue by bossanova808** [gorlins/zenapi#1]
I use this lib in a Kodi addon...just wondering if you have any thoughts on updating it to support the newer API at all?

**Comment by bossanova808** [comment]
Actually doesn't look like there's likely to be breaking changes in 1.7 or 1.8 really, but still curious if you have any plans to update this.  No dramas if not, of course.

**Comment by gorlins** [comment]
Unfortunately I haven't looked at this code in a long time - glad to know it's getting use though!  Last time I bumped the API version there were no issues, but I haven't looked at what's actually changing.  I suspect it would only be minor changes if any, would be happy to pull in any changes as necessary

**Comment by agustinjch** [comment]
I checked, and the only change that has to be made is change 1.6 for 1.8 in the _zapi.py file.

**Comment by gorlins** [comment]
resolved by #2
